### ISSUE TITLE
Project had an error : https://github.com/null/actions

### ISSUE THREAD

**Issue by kakamband** [francis-du/url-shortener#15]
Hi Francis,
After deploy process being start tell me :
Project had an error
Error
Congratulations, url-shortener is now deploying!
This may take a few minutes. Check your project repository, visit your new Worker, or learn more about Workers below.
waiting for your response
finest regards

**Comment by francis-du** [comment]
Hey guy,

Thanks for your report.

I also found that today, but I don't' know how to fix it.I think it a problem from Cloudflare Workers.I will fix it latrer.You can self-deploy as a template project and set your configurations. There are some docs for you,I hope it can help you.

[Cloudflare Workers](https://developers.cloudflare.com/workers/)

[Short.io Api](https://developers.short.io/docs)

If you have other questions, you can ask me here.

Happy a nice day,
Francis

**Comment by francis-du** [comment]
[There is officer bug report](https://github.com/cloudflare/workers.cloudflare.com/issues/132)

**Comment by francis-du** [comment]
https://github.com/cloudflare/workers.cloudflare.com/issues/132

**Comment by francis-du** [comment]
Deploy Button is  [here](https://github.com/signalnerve/deploy.workers.cloudflare.com)

**Comment by eidam** [comment]
fix has been merged :)

**Comment by francis-du** [comment]
> fix has been merged :)

Thanks for your replay.ᥬ☺᭄
